name: Showcase
on:
  push:
    branches:
      - master
env:
  SHOWCASE_ENV: lol
jobs:
  build:
    name: TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: show pipeline environemnt
        run: ls
