name: Showcase
on:
  push:
    branches:
      - master
env:
  SHOWCASE_ENV: lol
jobs:
  build:
    name: TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - id: install_npm_dependencies
        run: npm install
      - id: run_tests
        run: npm run test
      - id: run_lint
        run: npm run lint
      - id: create_docker_file
        run: docker run -p 8080:8080 --name "node_runner" node-container:v0.0.1
      - id: tag_docker_file
        run: docker tag node-container:v0.0.1 pietera/noderunner:latest
      - id: tag_docker_file
        run: docker push pietera/noderunner:latest
      - id: login_to_docker_hub
        run: docker login -u pietera -p ${{DOCKER_HUB_PASS}}
      - id: push_docker_file
        run: docker push pietera/noderunner:latest
